# Generated by Django 4.1.7 on 2023-03-25 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "address1",
                    models.CharField(max_length=120, verbose_name="Address line 1"),
                ),
                (
                    "address2",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Address line 2"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(max_length=12, verbose_name="Zip/Postal Code"),
                ),
                ("city", models.CharField(max_length=120)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("gh", "Ghana"),
                            ("us", "United States"),
                            ("uk", "United Kingdom"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
