# Generated by Django 4.1.7 on 2023-03-13 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_producttag_productimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="product_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="productimage",
            old_name="product_thumbnail",
            new_name="thumbnail",
        ),
    ]
