# Generated by Django 4.1.7 on 2023-03-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_product_image_productimage_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producttag",
            old_name="is_active",
            new_name="active",
        ),
    ]
