# Generated by Django 4.1.7 on 2023-03-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_is_active_producttag_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producttag",
            name="products",
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(blank=True, to="main.producttag"),
        ),
    ]
